# files to build simple debian meta packages
#
# http://wiki.debian.org/CreateDummyPackage
# equivs-build package-minimal 

ALL= bbbike-world bbbike-world-debian bbbike-world-perlmodules bbbike-world-javalibs

all:
	for i in ${ALL}; do \
	  echo `pwd`/$$i; \
	done

