###############################################################
# Wolfram Schneider, Aug 2008
#
# Get and convert OpenStreetMap.org data to BBBike
#
# For more information about BBBike, visit http://www.bbbike.de
#


MAX_PARALLELS_OSM_DOWNLOADS=	1
NICE=		nice -n 5
PERL=		perl
OSM2BBD_MAPTYPE=	#-map bbbike	
OSM_SOCKS_PROXY=	# --socksproxy=socks://localhost:1080
DOWNLOADOSM=	${PERL} ./miscsrc/downloadosm --debug=2 --step=0.02 ${OSM_SOCKS_PROXY}
OSM2BBD=	${PERL} ./miscsrc/osm2bbd -f --debug=0 ${OSM2BBD_MAPTYPE} -ignore-unhandled -ignore-underline -experiment add_postal_code -experiment polar_coord_hack
MAX_CPU=	`world/bin/ncpu`
MAX_CPU2=	`world/bin/ncpu -1`
GXARGS=		`which gxargs xargs | head -1`
BBBIKE_WEB_DIR= ./
OSM_DIR=	osm
DATA_OSM_DIR=	data-osm
DATA_OSM_BBBIKE_DIR=	data-osm.bbbike
OSMBIKE_DATA=	${DATA_OSM_BBBIKE_DIR}.tgz

CITIES=		\
	Berlin \
	CambridgeMa \
	Ruegen \
	SanJose \
	Copenhagen \
	Hamburg \
	Frankfurt \
	Prag \
	Tuscon \
	Toronto \
	Dresden \
	Dortmund \
	Bonn \
	Duisburg \
	London \
	Koeln \
	Duesseldorf \
	Portland \
	Hannover \
	Mannheim \
	Lissabon \
	Madison \
	Providence \
	Bremen \
	Rotterdam \
	PaloAlto \
	Reval \
	Montreal \
	Wien \
	SanFrancisco \
	Miami \
	Mainz \
	Paris \
	DenHaag \
	FortCollins \
	Amsterdam \
	NewYork \
	Seattle \
	Karlsruhe \
	Helsinki \
	Leipzig \
	Bielefeld \
	SanktPetersburg \
	Darmstadt \
	Bruessel \
	Rostock \
	Aarhus \
	Chicago \
	Cottbus \
	Zuerich \
	Stockholm \
	Danzig \
	Vancouver \
	Jena \
	Budapest \
	Strassburg \
	Luebeck \
	Basel \
	Sofia \
	Erlangen \
	Aachen \
	Groningen \
	Freiburg \
	Austin \
	Kiew \
	Dublin \
	Boulder \
	Goettingen \
	Stettin \
	Laibach \
	Oslo \
	Chemnitz \
	Erfurt \
	Cambridge \
	Barcelona \
	Zagreb \
	Muenster \
	SantaCruz \
	CraterLake \
	Riga \
	Davis \
	Krakau \
	Kaunas \
	Corvallis \
	BrandenburgHavel \
	Goerlitz \
	Turin \
	FrankfurtOder \
	WarenMueritz \
	Sarajewo \
	Colmar \
	Kassel \

#
# opensearch suggestion service for
# the world:
# 
OSM_AREAS_OPENSEARCH=data-opensearch2
OSM_AREAS_LARGE=\
	planet.osm.bz2 \
	north-america.osm.bz2 \

OSM_AREAS= \
	germany.osm.bz2 \
	${OSM_AREAS_LARGE} \
	australia-oceania.osm.bz2 \
	south-america.osm.bz2 \
	africa.osm.bz2 \
	central-america.osm.bz2 \
	europe.osm.bz2 \

all: help

convert-all: convert convert-workarounds

tarball: 
	${MAKE} -f Makefile.osm DATA_OSM_DIR=${DATA_OSM_BBBIKE_DIR} OSM2BBD_MAPTYPE="-map bbbike" convert-all 
	${MAKE} -f Makefile.osm DATA_OSM_DIR=${DATA_OSM_BBBIKE_DIR} _tarball

_tarball:
	tar cf - ${DATA_OSM_BBBIKE_DIR} | gzip > ${OSMBIKE_DATA}.tmp
	mv -f ${OSMBIKE_DATA}.tmp ${OSMBIKE_DATA}
	mkdir -p ../bbbike-macos/download
	cp -f ${OSMBIKE_DATA} ../bbbike-macos/download

cities:
	@for i in `perl -e 'print "x " x 16'`; do ${MAKE} -f Makefile.osm _cities; done
	${MAKE} -f Makefile.osm _cities_complete

_cities2:
	@for i in ${CITIES}; do \
	    ${MAKE} -f Makefile.osm $$i-download || \
	    ${MAKE} -f Makefile.osm $$i-download || \
	    ${MAKE} -f Makefile.osm $$i-download || \
	    ${MAKE} -f Makefile.osm $$i-download || \
	    ${MAKE} -f Makefile.osm $$i-download || \
		echo "please run me again: $$i"; \
	done

_cities:
	@echo ${CITIES} | \
		perl -npe 's/\s+/-download /g' | \
		xargs -n 1 -P ${MAX_PARALLELS_OSM_DOWNLOADS} ${MAKE} -f Makefile.osm

_cities_complete:
	${MAKE} -f Makefile.osm `echo ${CITIES} | perl -npe 's/\s+/-download /g'`

city-count:
	@echo ${CITIES}  | wc -w

city-population:
	@for i in ${CITIES}; do \
		printf "$$i "; \
		find osm/$$i -name '*.gz' -print0 | xargs -0 -n16 -P ${MAX_CPU} gzip -dc | egrep population | \
			perl -e 'while(<>) { s,.*:,,; print "$$1\n" if /(\d+)/ }; print "0\n" ' | sort -n | sort -u | awk '{ s += $$1 } END { print s }'; \
	done

update-city-population:
	${MAKE} -s -f Makefile.osm city-population | sort -k 2 -nr | perl -npe 's/ /:/' > world/misc/population.csv


# using GNU xargs -P parallel
osm-areas:
	#rm -rf ${OSM_AREAS_OPENSEARCH}.old
	#if test -e ${OSM_AREAS_OPENSEARCH}; then mv ${OSM_AREAS_OPENSEARCH} ${OSM_AREAS_OPENSEARCH}.old; fi
	mkdir -p ${OSM_AREAS_OPENSEARCH}
	cd ${OSM_AREAS_OPENSEARCH} && mkdir -p `echo ${OSM_AREAS} | perl -npe 's/\.osm\.bz2//g'`
	echo ${OSM_AREAS} " " | \
	  perl -ne 'chomp; foreach (split) { print qq{PATH=\$$PATH:`pwd`/world/bin world/bin/osm2suggestions ../osm/download/$$_ '${OSM_AREAS_OPENSEARCH}'/$$_\0} }' | \
	  ${NICE} ${GXARGS} -0 -n1 -P${MAX_CPU2} sh -c

osm-places:
	mkdir -p ${OSM_AREAS_OPENSEARCH}
	cd ${OSM_AREAS_OPENSEARCH} && mkdir -p `echo ${OSM_AREAS} | perl -npe 's/\.osm\.bz2/-places/g'`
	echo ${OSM_AREAS} " " | \
	  perl -ne 'chomp; foreach (split) { $$file=$$_; $$dir=$$file; $$dir =~ s/(\.osm)?(\.(gz|bz2))?$$/-places/; print qq{PATH=\$$PATH:`pwd`/world/bin world/bin/osm2places-suggestions ../osm-streetnames/download/geofabrik/$$file '${OSM_AREAS_OPENSEARCH}'/$$dir\0} }' | \ 
	  ${NICE} ${GXARGS} -0 -n1 -P${MAX_CPU} sh -c 


convert: _convert convert-workarounds
# using GNU xargs -P parallel
_convert:
	rm -rf ${DATA_OSM_DIR}.old
	if test -e ${DATA_OSM_DIR}; then mv ${DATA_OSM_DIR} ${DATA_OSM_DIR}.old;  fi
	mkdir -p ${DATA_OSM_DIR}
	echo ${CITIES} " " | perl -npe 's/\s+/-convert /g' | \
	  ${NICE} ${GXARGS} -n 1 -P ${MAX_CPU} ${MAKE} -f Makefile.osm

check:
	for i in ${CITIES}; do echo ${DATA_OSM_DIR}/$$i; done | \
	  ${NICE} ${GXARGS} -n 1 -P ${MAX_CPU} ./miscsrc/check_bbd --debug=0 -dir

convert-workarounds: osm2bbd-workarounds

osm2bbd-workarounds opensearch: opensearch-bbbike
	for i in ${CITIES}; do echo $$i; done | \
	  ${NICE} ${GXARGS} -n 1 -P ${MAX_CPU} world/bin/osm2bbd-workarounds ${DATA_OSM_DIR}

opensearch-bbbike:
	world/bin/opensearch-suggestion --gps=0 --input-charset=iso-8859-1 < data/strassen > data/opensearch.streetnames


_c = ${CITIES}
_cd = $(_c:=-download)
_cc = $(_c:=-convert)

DB=world/bin/bbbike-db

$(_cd):
	c=`basename $@ -download`; \
		mkdir -p ${OSM_DIR}/$$c; \
		${DOWNLOADOSM} -o ${OSM_DIR}/$$c -- `${DB} --coord $$c`

$(_cc):
	#c=`basename $@ -convert`; ${OSM2BBD} -centerdelta `${DB} --centerdelta $$c` -lang `${DB} --lang $$c` -o ${DATA_OSM_DIR}/$$c ${OSM_DIR}/$$c
	c=`basename $@ -convert`; ${OSM2BBD} -lang `${DB} --lang $$c` -o ${DATA_OSM_DIR}/$$c ${OSM_DIR}/$$c

${CITIES}:
	${MAKE} -f Makefile.osm $@-download $@-convert
	
######################################################################
rsync-osm:
	rsync -azv --exclude='*.bak' --delete --max-delete=512 ${DATA_OSM_DIR} osm bbbike.org:/usr/local/www/bbbike.org
	rsync -azv --exclude='*.bak' data/opensearch.streetnames bbbike.org:/usr/local/www/bbbike.org/data


create-bbbike-web-symlinks-bbbike.en.cgi:
	cd ${BBBIKE_WEB_DIR}/cgi && ln -fs bbbike.cgi bbbike.en.cgi

create-bbbike-web-symlinks: create-bbbike-web-symlinks-bbbike.en.cgi
	cd ${BBBIKE_WEB_DIR}/cgi && \
	for city in ${CITIES}; do \
		ln -fs world.cgi $$city.cgi; \
		ln -fs world.cgi $$city.en.cgi; \
		ln -fs world.cgi.config $$city.cgi.config; \
	done
	ln -fs world/misc/index.html ${BBBIKE_WEB_DIR}
	ln -fs world/misc/doc.html ${BBBIKE_WEB_DIR}
	ln -fs world/misc/bbbike-world.kml ${BBBIKE_WEB_DIR}
	ln -fs world/misc/streets.html ${BBBIKE_WEB_DIR}
	ln -fs ../world/misc/world.cgi.config ${BBBIKE_WEB_DIR}/cgi
	ln -fs ../world/bin/world.cgi ${BBBIKE_WEB_DIR}/cgi
	ln -fs ../world/bin/streets.cgi ${BBBIKE_WEB_DIR}/cgi

TAGCLOUD=	world/bin/tagcloud 
tagcloud:
	${DB} --area=de | perl -npe 's,^,^,; s,$$,:,' > tmp/cities.tmp && \
		egrep -f tmp/cities.tmp world/misc/population.csv | ${TAGCLOUD} --lang=de > tmp/cities.de
	${DB} --area=eu | perl -npe 's,^,^,; s,$$,:,' > tmp/cities.tmp && \
		egrep -f tmp/cities.tmp world/misc/population.csv | ${TAGCLOUD} --lang=en > tmp/cities.eu
	${DB} --area=other | perl -npe 's,^,^,; s,$$,:,' > tmp/cities.tmp && \
		egrep -f tmp/cities.tmp world/misc/population.csv | ${TAGCLOUD} --lang=en > tmp/cities.other
	rm -f tmp/cities.tmp

kml:
	world/bin/bbbike-world-kml world/misc/cities.csv > world/misc/bbbike-world.kml

scp rsync rsync-tgz:
	rsync -av ${OSMBIKE_DATA} wolfram.schneider.org:www/src/bbbike

clean:
	rm -rf ${DATA_OSM_DIR} ${DATA_OSM_BBBIKE_DIR}
	mkdir ${DATA_OSM_DIR} ${DATA_OSM_BBBIKE_DIR}

dist-clean devel-clean distclean: clean
	rm -rf osm
	mkdir -p osm

help:
	@echo "usage: make [ help | cities | convert | rsync-tgz | rsync-osm ]"
	@echo "            [ tarball | clean | dist-clean | create-bbbike-web-symlinks ]"
	@echo "            [ convert | convert-workarounds | convert-all | opensearch | kml ]"
	@echo "            [ city-count | city-population | update-city-population ]"
	@echo "            [ osm-areas | osm-places ]"
	@echo ""
	@echo "            [ ${CITIES} ]"

