###############################################################
# Copyright (c) 2008-2010 Wolfram Schneider, http://bbbike.org
#
# Get and convert OpenStreetMap.org data to BBBike
#
# For more information about BBBike, visit http://www.bbbike.de
#


MAX_PARALLELS_OSM_DOWNLOADS=	1
NICE=		nice -n 15
PERL=		perl
OSM2BBD_MAPTYPE=	#-map bbbike	
OSM_SOCKS_PROXY=	 --socksproxy=socks://localhost:1080
OSM_TIMEOUT=	--timeout=45
DOWNLOADOSM=	${PERL} ./miscsrc/downloadosm --debug=0 ${OSM_SOCKS_PROXY} ${OSM_TIMEOUT}
OSM2BBD=	${PERL} ./miscsrc/osm2bbd -f --debug=0 ${OSM2BBD_MAPTYPE} -ignore-unhandled -ignore-underline -experiment add_postal_code -experiment polar_coord_hack
MAX_CPU=	`world/bin/ncpu`
MAX_CPU2=	`world/bin/ncpu -1`
GXARGS=		${NICE} `which gxargs xargs | head -1`
BBBIKE_WEB_DIR= ./
OSM_DIR=	osm
OSP_DIR=	osp
DATA_OSM_DIR=	data-osm
DATA_OSM_BBBIKE_DIR=	data-osm.bbbike
OSMBIKE_DATA=	${DATA_OSM_BBBIKE_DIR}.tgz
DATA_DIR=	data

GZIP:=             $(shell which pigz gzip | head -1)
BZIP2:=            $(shell which pbzip2 bzip2 | head -1)

CITIES=		\
	Berlin \
	Dortmund \
	WashingtonDC \
	Moscow \
	Hamburg \
	Paris \
	Marseille \
	Duisburg \
	Muenchen \
	Toronto \
	Ruegen \
	Orlando \
	Mannheim \
	Sydney \
	SanJose \
	Frankfurt \
	Denver \
	Copenhagen \
	CambridgeMa \
	Prag \
	Strassburg \
	Perth \
	Sacramento \
	Bonn \
	Ottawa \
	Albuquerque \
	Duesseldorf \
	Dresden \
	Rotterdam \
	Koeln \
	Wien \
	Amsterdam \
	CapeTown \
	London \
	PhnomPenh \
	PaloAlto \
	Stettin \
	Tokyo \
	Darmstadt \
	DenHaag \
	Warschau \
	Hannover \
	Groningen \
	Saigon \
	Santiago \
	Nuernberg \
	Mainz \
	Montreal \
	Helsinki \
	Rostock \
	Bremen \
	SanktPetersburg \
	Tuscon \
	Seoul \
	Leipzig \
	Portland \
	Singapore \
	Reval \
	SanFrancisco \
	Madison \
	Victoria \
	Karlsruhe \
	SantaBarbara \
	Zuerich \
	Bielefeld \
	Bogota \
	MexicoCity \
	Kassel \
	Vancouver \
	Zagreb \
	Bamberg \
	Stockholm \
	SantaCruz \
	Miami \
	Seattle \
	RiodeJaneiro \
	Bruessel \
	NewYork \
	Jena \
	Providence \
	Luebeck \
	Genf \
	Kiel \
	Budapest \
	FortCollins \
	Colmar \
	Aarhus \
	Breslau \
	Danzig \
	Chicago \
	Freiburg \
	Erlangen \
	Cottbus \
	Kiew \
	Beijing \
	Aachen \
	Barcelona \
	Cairo \
	Baghdad \
	Dublin \
	Posen \
	Oldenburg \
	Basel \
	Chemnitz \
	Magdeburg \
	Eugene \
	Goettingen \
	Sofia \
	Kattowitz \
	Lissabon \
	Trondheim \
	Tehran \
	Cambridge \
	Laibach \
	Bangkok \
	Oslo \
	Boulder \
	Erfurt \
	Muenster \
	Jerusalem \
	Gleiwitz \
	Austin \
	Turin \
	Istanbul \
	Riga \
	Davis \
	Krakau \
	Goerlitz \
	Beirut \
	Kaunas \
	CraterLake \
	BrandenburgHavel \
	Sarajewo \
	WarenMueritz \
	FrankfurtOder \
	Corvallis \
	Baku \
	UlanBator \
	Glasgow \
	Edinburgh \
	Leeds \
	Birmingham \
	Liverpool \
	Sheffield \
	Bristol \
	Manchester \

#
# opensearch suggestion service for
# the world:
# 
OSM_AREAS_OPENSEARCH=data-opensearch-places
OSM_AREAS_LARGE=\
	../osm-streetnames/download/planet-latest.osm.bz2 \

OSM_AREAS= \
	../osm-streetnames/download/geofabrik/europe/germany.osm.bz2 \
	${OSM_AREAS_LARGE} \
	../osm-streetnames/download/geofabrik/australia-oceania.osm.bz2 \
	../osm-streetnames/download/geofabrik/south-america.osm.bz2 \
	../osm-streetnames/download/geofabrik/africa.osm.bz2 \
	../osm-streetnames/download/geofabrik/central-america.osm.bz2 \
	../osm-streetnames/download/geofabrik/europe.osm.bz2 \

# for tests only
OSM_AREAS2= \
	../osm-streetnames/download/geofabrik/europe/germany/baden-wuerttemberg.osm.bz2 \
	../osm-streetnames/download/geofabrik/europe/germany/bayern.osm.bz2 \
	../osm-streetnames/download/geofabrik/europe/germany/berlin.osm.bz2 \
	../osm-streetnames/download/geofabrik/europe/germany/brandenburg.osm.bz2 \
	../osm-streetnames/download/geofabrik/europe/germany/bremen.osm.bz2 

OSM_AREAS3= \
	${OSM_AREAS_LARGE} \


all: help

convert-wgs84: convert create-osp osm2bbd-workarounds-streets bbbike2wgs84

convert-bbbike: 
	${MAKE} -f Makefile.osm DATA_OSM_DIR=${DATA_OSM_BBBIKE_DIR} OSM2BBD_MAPTYPE="-map bbbike" convert
	rm -f ${DATA_OSM_BBBIKE_DIR}/*/opensearch-suggestion
	${MAKE} -f Makefile.osm DATA_OSM_DIR=${DATA_OSM_BBBIKE_DIR} _tarball

_tarball:
	tar cf - ${DATA_OSM_BBBIKE_DIR} | ${GZIP} > ${OSMBIKE_DATA}.tmp
	mv -f ${OSMBIKE_DATA}.tmp ${OSMBIKE_DATA}
	mkdir -p ../bbbike-macos/download
	cp -f ${OSMBIKE_DATA} ../bbbike-macos/download
	tar cf - ${DATA_DIR} | ${BZIP2} > ${DATA_DIR}.tbz.tmp
	mv -f ${DATA_DIR}.tbz.tmp ${DATA_DIR}.tbz

cities:
	@for i in `perl -e 'print "x " x 2'`; do ${MAKE} -f Makefile.osm _cities; done
	${MAKE} -f Makefile.osm cleanup-osm-error
	${MAKE} -f Makefile.osm _cities_complete
	${MAKE} -f Makefile.osm check-osm

_cities:
	@echo ${CITIES} | \
		perl -npe 's/\s+/-download /g' | \
		xargs -n 1 -P ${MAX_PARALLELS_OSM_DOWNLOADS} ${MAKE} -f Makefile.osm

_cities_complete:
	${MAKE} -f Makefile.osm OSM_TIMEOUT="--timeout=300" `echo ${CITIES} | perl -npe 's/\s+/-download /g'`

city-count:
	@echo ${CITIES}  | wc -w

city-reorder:
	@cd osm; du -ks * | sort -nr


# using GNU xargs -P parallel
osm-areas2:
	#rm -rf ${OSM_AREAS_OPENSEARCH}.old
	#if test -e ${OSM_AREAS_OPENSEARCH}; then mv ${OSM_AREAS_OPENSEARCH} ${OSM_AREAS_OPENSEARCH}.old; fi
	mkdir -p ${OSM_AREAS_OPENSEARCH}
	cd ${OSM_AREAS_OPENSEARCH} && mkdir -p `echo ${OSM_AREAS} | perl -npe 's/\.osm\.bz2//g'`
	echo ${OSM_AREAS} " " | \
	  perl -ne 'chomp; foreach (split) { print qq{PATH=\$$PATH:`pwd`/world/bin world/bin/osm2suggestions ../osm/download/$$_ '${OSM_AREAS_OPENSEARCH}'/$$_\0} }' | \
	  ${GXARGS} -0 -n1 -P${MAX_CPU2} sh -c

# faster than planet-streets
planet-places:
	@mkdir -p ${OSM_AREAS_OPENSEARCH}
	@PATH=$$PATH:`pwd`/world/bin; \
	for i in ${OSM_AREAS}; do \
		printf "./world/bin/planet-places-suggestions ${OSM_AREAS_OPENSEARCH}/`basename $$i .osm.bz2`-places $$i\0"; \
	done | ${GXARGS} -0 -n1 -P${MAX_CPU2} sh -c

planet-streets:
	@mkdir -p ${OSM_AREAS_OPENSEARCH}
	@PATH=$$PATH:`pwd`/world/bin; \
	for i in ${OSM_AREAS}; do \
		printf "./world/bin/planet-streets-suggestions ${OSM_AREAS_OPENSEARCH}/`basename $$i .osm.bz2` $$i\0"; \
	done | ${GXARGS} -0 -n1 -P${MAX_CPU2} sh -c

##########################################################################################
# check if the downloaded OSM files are valid
#
check-osm: check-osm-gzip check-osm-error

check-osm-gzip:
	@find ${OSM_DIR} -name '*.gz' -print0 | ${GXARGS} -0 -n32 -P${MAX_CPU} gzip -t

check-osm-error:
	@find ${OSM_DIR} -name '*.gz' -print0 | ${GXARGS} -0 -n32 -P${MAX_CPU} zegrep -l '<error>' || true

cleanup-osm-error:
	${MAKE} -f Makefile.osm check-osm 2>&1 | grep ^gzip | awk '{ print $$2 }' | perl -npe 's,:,,' | sort -u | xargs rm -f
	@find ${OSM_DIR} -name '*.gz' -print0 | ${GXARGS} -0 -n32 -P${MAX_CPU} zegrep -l '<error>' | xargs rm -f


convert: _convert convert-workarounds
# using GNU xargs -P parallel
_convert:
	rm -rf ${DATA_OSM_DIR}.old
	if test -e ${DATA_OSM_DIR}; then mv ${DATA_OSM_DIR} ${DATA_OSM_DIR}.old;  fi
	mkdir -p ${DATA_OSM_DIR}
	echo ${CITIES} " " | perl -npe 's/\s+/-convert /g' | \
	   ${GXARGS} -n 1 -P ${MAX_CPU} ${MAKE} -f Makefile.osm

check:
	for i in ${CITIES}; do echo ${DATA_OSM_DIR}/$$i; done | \
	  ${GXARGS} -n 1 -P ${MAX_CPU} ./miscsrc/check_bbd --debug=0 -dir

convert-workarounds: osm2bbd-workarounds

osm2bbd-workarounds opensearch: opensearch-bbbike
	for i in ${CITIES}; do echo $$i; done | \
	  ${GXARGS} -n 1 -P ${MAX_CPU} world/bin/osm2bbd-workarounds ${DATA_OSM_DIR}

opensearch-bbbike:
	world/bin/opensearch-suggestion --gps=0 --input-charset=iso-8859-1 < data/strassen > data/opensearch.streetnames

osm2bbd-workarounds-streets: 
	for i in ${CITIES}; do echo $$i; done | \
	  ${GXARGS} -n 1 -P ${MAX_CPU} world/bin/osm2bbd-workarounds-streets ${DATA_OSM_DIR}


_c = ${CITIES}
_cd = $(_c:=-download)
_cc = $(_c:=-convert)
_cw = $(_c:=-workarounds)

DB=world/bin/bbbike-db

$(_cd):
	c=`basename $@ -download`; mkdir -p ${OSM_DIR}/$$c; \
		${DOWNLOADOSM} --step=`${DB} --step $$c` -o ${OSM_DIR}/$$c -- `${DB} --coord $$c`

#c=`basename $@ -convert`; ${OSM2BBD} -centerdelta `${DB} --centerdelta $$c` -lang `${DB} --lang $$c` -o ${DATA_OSM_DIR}/$$c ${OSM_DIR}/$$c
$(_cc):
	c=`basename $@ -convert`; rm -rf ${DATA_OSM_DIR}/$$c; ${OSM2BBD} -lang `${DB} --lang $$c` -o ${DATA_OSM_DIR}/$$c ${OSM_DIR}/$$c

$(_cw):
	c=`basename $@ -workarounds`; world/bin/osm2bbd-workarounds ${DATA_OSM_DIR} $$c
	c=`basename $@ -workarounds`; world/bin/osm2bbd-workarounds-streets ${DATA_OSM_DIR} $$c

${CITIES}:
	${MAKE} -f Makefile.osm $@-download $@-convert $@-workarounds
	
######################################################################
rsync-osm:
	rsync -azv --exclude='*.bak' --delete --max-delete=512 ${DATA_OSM_DIR} ${OSM_AREAS_OPENSEARCH} osm osp bbbike.org:/usr/local/www/bbbike.org
	rsync -azv --exclude='*.bak' data/opensearch.streetnames bbbike.org:/usr/local/www/bbbike.org/data

rsync-osm-devel rsync-osm-dev:
	rsync -azv --delete --max-delete=512 bbbike.org:projects/bbbike/osm .


create-bbbike-web-symlinks-bbbike.en.cgi:
	cd ${BBBIKE_WEB_DIR}/cgi && ln -fs bbbike.cgi bbbike.en.cgi

create-bbbike-web-symlinks: create-bbbike-web-symlinks-bbbike.en.cgi
	cd ${BBBIKE_WEB_DIR}/cgi && \
	for city in ${CITIES} berlin; do \
		ln -fs world.cgi $$city.cgi; \
		ln -fs world.cgi $$city.en.cgi; \
		ln -fs world.cgi.config $$city.cgi.config; \
	done
	ln -fs world/misc/index.html ${BBBIKE_WEB_DIR}
	ln -fs world/misc/index.de.html ${BBBIKE_WEB_DIR}
	ln -fs world/misc/index.m.html ${BBBIKE_WEB_DIR}
	ln -fs world/misc/doc.html ${BBBIKE_WEB_DIR}
	ln -fs world/misc/community.html ${BBBIKE_WEB_DIR}
	ln -fs world/misc/community.de.html ${BBBIKE_WEB_DIR}
	ln -fs world/misc/app.html ${BBBIKE_WEB_DIR}
	ln -fs world/misc/bbbike-world.kml ${BBBIKE_WEB_DIR}
	ln -fs world/misc/streets.html ${BBBIKE_WEB_DIR}
	ln -fs world/Makefile.osm ${BBBIKE_WEB_DIR}
	ln -fs Makefile.osm Makefile
	ln -fs ../world/misc/world.cgi.config ${BBBIKE_WEB_DIR}/cgi
	ln -fs ../world/bin/world.cgi ${BBBIKE_WEB_DIR}/cgi
	ln -fs ../world/bin/streets.cgi ${BBBIKE_WEB_DIR}/cgi
	ln -fs images/srtbike.ico favicon.ico # buggy browsers

TAGCLOUD=	world/bin/tagcloud 
CITIES_DB=	world/misc/cities.csv

tagcloud:
	${TAGCLOUD} --area=de < ${CITIES_DB} > tmp/de.cities.de
	${TAGCLOUD} --area=eu < ${CITIES_DB} > tmp/de.cities.eu
	${TAGCLOUD} --area=other --level=9 < ${CITIES_DB} > tmp/de.cities.other
	${TAGCLOUD} --lang=en --area=de < ${CITIES_DB} > tmp/en.cities.de
	${TAGCLOUD} --lang=en --area=eu < ${CITIES_DB} > tmp/en.cities.eu
	${TAGCLOUD} --lang=en --area=other --level=9 < ${CITIES_DB} > tmp/en.cities.other
	world/bin/mobile-links --split-city-names=1 --lang=de < ${CITIES_DB} > tmp/option.de
	world/bin/mobile-links --local-names=1 --split-city-names=1 --lang=en < ${CITIES_DB} > tmp/option.en

kml:
	world/bin/bbbike-world-kml ${CITIES_DB} > world/misc/bbbike-world.kml

bbbike2wgs84:
	./world/bin/bbbike2wgs84

planet-download:
	download_script=`pwd`/world/bin/planet-download; cd ../osm-streetnames/download && $$download_script

planet-geofabrik-download:
	download_script=`pwd`/world/bin/planet-geofabrik-download; \
		cd ../osm-streetnames/download && $$download_script

create-osp:
	rm -rf ${OSP_DIR}
	mkdir ${OSP_DIR}
	./world/bin/bbbike-world-opensearch-plugin --streets ${OSP_DIR} world/misc/streets.csv
	./world/bin/bbbike-world-opensearch-plugin ${OSP_DIR} ${CITIES_DB}
	
scp rsync rsync-tgz:
	rsync -av ${OSMBIKE_DATA} wolfram.schneider.org:www/src/bbbike
	rsync -av ${DATA_DIR}.tbz wolfram.schneider.org:www/src/bbbike/${DATA_OSM_DIR}

clean:
	rm -rf ${DATA_OSM_DIR} ${DATA_OSM_BBBIKE_DIR}
	mkdir ${DATA_OSM_DIR} ${DATA_OSM_BBBIKE_DIR}

dist-clean devel-clean distclean: clean
	rm -rf osm
	mkdir -p osm

help:
	@echo "usage: make [ help | cities | rsync-tgz | rsync-osm | rsync-osm-dev ]"
	@echo "            [ clean | dist-clean | create-osp | tagcloud | bbbike2wgs84 ]"
	@echo "            [ osm2bbd-workarounds-streets | create-bbbike-web-symlinks | kml ]"
	@echo "            [ convert-wgs84 | convert-bbbike ]"
	@echo "            [ city-count | city-reorder | check-osm | cleanup-osm-error ]"
	@echo "            [ planet-download | planet-geofabrik-download ]"
	@echo "            [ planet-streets | planet-places ]"
	@echo ""
	@echo "            [ "`perl -e 'print join " ", sort @ARGV' ${CITIES}` "]"

