#!/bin/sh
### BEGIN INIT INFO
# Provides:          renderd-slowstart
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Mapnik rendering daemon
# Description:       Mapnik rendering daemon.
### END INIT INFO

# symlink or copy to /etc/init.d
# sudo update-rc.d renderd-slowstart  defaults 30

( sleep 20; sh /etc/init.d/renderd "$@" ) &

