#!/bin/sh
# Copyright (c) 2011-2013 Wolfram Schneider, http://bbbike.org
#
# bbbike-memory - check perl memory usage of a city

: ${data_osm=data-osm}
: ${debug=""}
: ${time=""} # time=time
: ${strace="strace -o bbbike.strace"} # 

# die on exit
#set -e

#############################################
# Strassburg
#
# http://www.bbbike.org/Strassburg/?start=Rue+de+la+Tour%2FRue+du+Muhlbruchel+%5B7.71584%2C48.57808%2C0%5D&via=&ziel=Pont+de+la+Dinsenm%C3%BChle%2FRue+des+Moulins+%5B7.74175%2C48.58069%2C0%5D&scope=
#
# "7.71584,48.57808"
# "7.74175,48.58069"


export i
for city 
do
  for i in 1; do
    rm -rf cache
    mkdir -p cache
    env DATA_DIR="data-osm/$city" BBBIKE_DATADIR="data-osm/$city" \
     $time $strace \
    perl -MDevel::Size=total_size -e \
	'
	   use List::Util qw(sum);
	   use Data::Dumper;
	   use lib "./lib";
	   #use BBBikeXS;

	   use Strassen;
	   use Strassen::StrassenNetz;
	   
           my $c1 = "7.71584,48.57808";
           my $c2 = "7.74175,48.58069";
	   StrassenNetz::use_data_format($ENV{i});
	   my $net=StrassenNetz->new(Strassen->new("strassen"));
           $net->make_net; 
	   print "data format: $ENV{i}, $ENV{DATA_DIR}: ", int(total_size($net)/1024/1024*10)/10, " MB\n";
	   my($path) = $net->search($c1, $c2);
    	   my(@route) = $net->route_to_name($path);
    	   my $dist1 = int sum map { $_->[StrassenNetz::ROUTE_DIST] } @route;
	   print "dist: $dist1\n";
	'
  done
done

