#!/bin/sh
# /etc/init.d/x11-common: set up the X server and ICE socket directories
### BEGIN INIT INFO
# Provides:          xvfb
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     S
# Default-Stop:
### END INIT INFO

set -e

PATH=/usr/bin:/bin
NAME=xvfb
TMPDIR=/tmp
display=101

. /lib/lsb/init-functions
if [ -f /etc/default/rcS ]; then
  . /etc/default/rcS
fi

[ -r /etc/default/$NAME ] && . /etc/default/$NAME

lockfile="$TMPDIR/.X${display}-lock"

case "$1" in
  start )
    Xvfb :${display} -ac -screen 0 1600x1200x24 > /tmp/xvfb-${display}-$(whoami).log 2>&1 &
    :
  ;;

  stop)
    if [ -e "$lockfile" ]; then
        pid=$(cat $lockfile)
        kill -TERM $pid
        sleep 0.5
        kill -9 $pid > /dev/null 2>&1 || true
    fi
  ;;
  
  restart ) $0 stop; $0 start ;;

  *)
    echo "Usage: /etc/init.d/xvfb { start | stop | restart }"
    exit 1
    ;;
esac

exit 0

