#!/bin/sh
# Copyright (c) Sep 2011-2015 Wolfram Schneider, http://bbbike.org
#
# usage: /etc/munin/plugins/bbbike-processes [ config ]
#
# get documentation with: perldoc /path/to/script

: << =cut

=head1 NAME

bbbike-processes  - Plugin to monitor if all processes are running

=head1 ABOUT

[...]

=head1 USAGE

[...]

=head1 CONFIGURATION

Configuration parameters for /etc/munin/plugin-conf.d/munin-node
if you need to override the defaults below:

 [bbbike-processes]
   env.warning   - Generate a warning if disk usage goes above this level
   env.critical  - Generate a critical if disk usage goes above this level
   env.process_names      - List of processes to monitor, separated by spaces

=cut


PATH=/bin:/usr/bin; export PATH

: ${process_names="lighttpd exim4 sshd ntpd"}

config=$1

if [ "$1" = "config" ]; then
    : ${warning=1:10}
    : ${critical=1:50}
     
    cat <<EOF
graph_title BBBike Processes
graph_vlabel BBBike Processes
graph_category bbbikesystem
graph_info BBBike Processes
graph_period minute
EOF

    for p in $process_names
    do
        echo "$p.label $p"
        echo "$p.warnings $warning"
        echo "$p.critical $critical"
    done

    exit 0
fi

for p in $process_names
do
    echo "$p.value" $(egrep "^${p}$" /proc/*/comm | wc -l)
done

