#!/bin/sh
# Copyright (c) Sep 2011-2017 Wolfram Schneider, https://bbbike.org
#
# usage: /etc/munin/plugins/bbbike-processes [ config ]
#
# get documentation with: perldoc /path/to/script

: << =cut

=head1 NAME

bbbike-processes  - Plugin to monitor if all processes are running

=head1 ABOUT

[...]

=head1 USAGE

[...]

=head1 CONFIGURATION

Configuration parameters for /etc/munin/plugin-conf.d/munin-node
if you need to override the defaults below:

 [bbbike-processes]
   env.warning   - Generate a warning if disk usage goes above this level
   env.critical  - Generate a critical if disk usage goes above this level
   env.process_names       - List of processes to monitor, separated by spaces
   env.process_names_d     - List of processes with trailing *d to monitor (e.g. ssh)
   env.process_names_opt   - List of optional processes to monitor
   env.process_names_opt_d - List of optional processes with trailing *d to monitor (e.g. varnish)

=cut


PATH=/bin:/usr/bin; export PATH
LANG="C"; export LANG

grep='grep -E -a'

# the file must exists in /etc/init.d or a dummy file in /etc/init.d/.<name>
# optional
: ${process_names_opt="lighttpd apache2 varnishncsa renderd postgres Xvfb memcached z3950proxy.pl java munin-cgi-graph hitch"}
# required
: ${process_names="exim4 munin-node"}

# daemons with 'd' prefix, e.g: ssh -> sshd
# optional
: ${process_names_opt_d="varnish"}
# required
: ${process_names_d="ssh ntp"}

config=$1

pname ()
{
    echo "$1" | sed 's/\./_/g'
}

if [ "$1" = "config" ]; then
    : ${warning=1:25}
    : ${critical=1:80}
     
    cat <<EOF
graph_title BBBike Processes
graph_vlabel BBBike Processes
graph_category bbbikesystem
graph_info BBBike Processes
graph_period minute
EOF

    for pp in $process_names $process_names_d
    do
	   p=$(pname $pp)
           echo "$p.label $p"
           echo "$p.warning $warning"
           echo "$p.critical $critical"
    done
    
    for pp in $process_names_opt $process_names_opt_d
    do
        if [ -e /etc/init.d/$pp -o -e /etc/init.d/.$pp ]; then
           p=$(pname $pp)
               echo "$p.label $p"
               echo "$p.warning $warning"
               echo "$p.critical $critical"
        fi
    done

    exit 0
fi

for pp in $process_names
do
  	p=$(pname $pp)
   	echo "$p.value" $($grep "^${pp}$" /proc/*/comm 2>/dev/null | wc -l)
done
for pp in $process_names_opt
do
    if [ -e /etc/init.d/$pp -o -e /etc/init.d/.$pp ]; then
    	p=$(pname $pp)
    	echo "$p.value" $($grep "^${pp}$" /proc/*/comm 2>/dev/null | wc -l)
    fi
done

for pp in $process_names_d
do
   	p=$(pname $pp)
   	echo "$p.value" $($grep "^${pp}d$" /proc/*/comm 2>/dev/null | wc -l)
done
for pp in $process_names_opt_d
do
    if [ -e /etc/init.d/$pp ]; then
    	p=$(pname $pp)
    	echo "$p.value" $($grep "^${pp}d$" /proc/*/comm 2>/dev/null | wc -l)
    fi
done

