#!/bin/sh
# Copyright (c) Sep 2011-2015 Wolfram Schneider, https://bbbike.org
#
# usage: /etc/munin/plugins/bbbike-processes [ config ]
#
# get documentation with: perldoc /path/to/script

: << =cut

=head1 NAME

bbbike-processes  - Plugin to monitor if all processes are running

=head1 ABOUT

[...]

=head1 USAGE

[...]

=head1 CONFIGURATION

Configuration parameters for /etc/munin/plugin-conf.d/munin-node
if you need to override the defaults below:

 [bbbike-processes]
   env.warning   - Generate a warning if disk usage goes above this level
   env.critical  - Generate a critical if disk usage goes above this level
   env.process_names      - List of processes to monitor, separated by spaces

=cut


PATH=/bin:/usr/bin; export PATH

: ${process_names="lighttpd exim4 apache2 varnishncsa renderd munin-node"}

# daemons with 'd' prefix, e.g: ssh -> sshd
: ${process_names_d="ssh varnish ntp"}

config=$1

pname ()
{
    echo "$1" | sed 's/\./_/g'
}

if [ "$1" = "config" ]; then
    : ${warning=1:25}
    : ${critical=1:80}
     
    cat <<EOF
graph_title BBBike Processes
graph_vlabel BBBike Processes
graph_category bbbikesystem
graph_info BBBike Processes
graph_period minute
EOF

    for pp in $process_names $process_names_d
    do
	if [ -e /etc/init.d/$pp ]; then
	   p=$(pname $pp)
           echo "$p.label $p"
           echo "$p.warning $warning"
           echo "$p.critical $critical"
	fi
    done

    exit 0
fi

for pp in $process_names
do
    if [ -e /etc/init.d/$pp ]; then
    	p=$(pname $pp)
    	echo "$p.value" $(egrep "^${pp}$" /proc/*/comm | wc -l)
    fi
done

for pp in $process_names_d
do
    if [ -e /etc/init.d/$pp ]; then
    	p=$(pname $pp)
    	echo "$p.value" $(egrep "^${pp}d$" /proc/*/comm | wc -l)
    fi
done

