#!/bin/sh
# Copyright (c) Sep 2011-2024 Wolfram Schneider, https://bbbike.org
#
# usage: /path/to/script [ config ]
#
# get documentation with: perldoc /path/to/script

: << =cut

=head1 NAME

bbbike-cities  - Plugin to monitor cities routes

=head1 CONFIGURATION

Configuration parameters for /etc/munin/plugin-conf.d/munin-node
if you need to override the defaults below:

 [bbbike-cities]
   env.warning   - Generate a warning if more routes are above this level
   env.critical  - Generate a critical if more routes are above this level

=cut


PATH="/bin:/usr/bin"; export PATH
LANG="C"; export LANG
grep='grep -E -a'

data_dir="/usr/local/www/bbbike.org/data-osm"
logfile="/var/log/lighttpd/bbbike.log"

config=$1

if [ "$1" = "config" ]; then
    : ${warning="20"}
    : ${critical="100"}
     
    cat <<EOF
multigraph BBBike city routes
graph_args --base 1024 --lower-limit 0
graph_title BBBike city routes
graph_vlabel BBBike city routes
graph_category bbbike
graph_info city routes
graph_period minute
EOF
    for ff in $(ls $data_dir)
    do
        echo "$ff.label $f"
        echo "$ff.min 0"
        echo "$ff.warning $warning"
        echo "$ff.critical $critical"
    done
    
    exit 0
fi

###########################################################


cities=$(mktemp /tmp/munin-bbbike.XXXXXXXXX)
# make sure we always print all regions with a value, otherwise we will get a "-nan" from munin
ls $data_dir | perl -ne 'chomp; print qq[1 2 3 4 5 "GET /$_/?start 8\n]' > $cities

trap 'rm -f $cities' 0

egrep -h '"GET /[a-zA-Z]+/\?[a-z]+' $logfile $cities | $grep -v cache | 
  awk '{ print $7 }'| perl -npe 's,\?.*,,; s,/,,g;' | sort | uniq -c | sort -k2 |
  awk '{ print $2 ".value", ($1 - 1) }'

exit 0

#EOF
