#!/bin/sh
# Copyright (c) Sep 2011-2023 Wolfram Schneider, https://bbbike.org
#
# usage: /path/to/script [ config ]
#
# get documentation with: perldoc /path/to/script


: << =cut

=head1 NAME

extract-download  - Plugin to monitor number download traffic

=head1 CONFIGURATION

Configuration parameters for /etc/munin/plugin-conf.d/munin-node
if you need to override the defaults below:

 [bbbike-extract-files]
   env.warning   - Generate a warning if traffic goes above this level
   env.critical  - Generate a critical if traffic goes above this level

=cut


set -e
PATH="/bin:/usr/bin"; export PATH
LANG="C"
log_dir="/var/log/lighttpd"
formats="bbbike garmin mapsforge mbtiles pmtiles organicmaps"
download="planet_latest planet_daily extract other ALL"

config=$1

if [ "$1" = "config" ]; then
    : ${warning="2500"}
    : ${critical="3500"}
     
    cat <<EOF
multigraph download
graph_title download traffic
graph_vlabel download traffic out
graph_category extractadmin
graph_period minute
EOF
    for i in $download
    do
        echo "$i.label $i"
        echo "$i.min 0"
    done


    cat <<EOF
multigraph precompute
graph_title precompute traffic
graph_vlabel precompute traffic out
graph_category extractadmin
graph_period minute
EOF
    for i in $formats
    do
        echo "$i.label $i"
        echo "$i.min 0"
    done

    exit 0
fi

cd $log_dir

trap 'rm -f $log_file' 0
days=30
log_file=$(mktemp /tmp/munin-extract-download.XXXXXXXX)
zcat -f $(ls -tr download* | tail -n $days) /dev/null | egrep -v '/html/|\?|/tmp/' | awk '{ if ($10 > 50*1024) { print $7, $10 } }' > $log_file

echo "multigraph download"
echo "planet_latest.value" 	$( egrep '^/osm/planet/planet-latest' $log_file  | awk 'BEGIN { a = 0 } { a += $2 } END { print a }' )
echo "planet_daily.value" 	$( egrep '^/osm/planet/planet-daily' $log_file   | awk 'BEGIN { a = 0 } { a += $2 } END { print a }' )
echo "extract.value" 		$( egrep '^/osm/extract/' $log_file              | awk 'BEGIN { a = 0 } { a += $2 } END { print a }' )
echo "other.value" 		$( egrep -v '^/osm/(extract|planet)/' $log_file  | awk 'BEGIN { a = 0 } { a += $2 } END { print a }' )
echo "ALL.value" 		$( cat $log_file                                 | awk 'BEGIN { a = 0 } { a += $2 } END { print a }' )

echo ""

echo "multigraph precompute"
for i in $formats
do
    echo "$i.value" $( egrep "/osm/$i/[^ ]+.zip " $log_file | awk 'BEGIN { a = 0 } { a += $2 } END { print a }' )
done

#EOF
