#!/bin/sh
# Copyright (c) Sep 2011-2021 Wolfram Schneider, https://bbbike.org
#
# usage: /etc/munin/plugins/extract-files [ config ]
#
# get documentation with: perldoc /path/to/script

: << =cut

=head1 NAME

extract-files  - Plugin to monitor number of files

=head1 ABOUT

[...]

=head1 USAGE

[...]

=head1 CONFIGURATION

Configuration parameters for /etc/munin/plugin-conf.d/munin-node
if you need to override the defaults below:

 [bbbike-extract-files]
   env.warning   - Generate a warning if number of files goes above this level
   env.critical  - Generate a critical if number of files goes above this level

=cut


PATH=/bin:/usr/bin; export PATH
extract_dir=/var/cache/extract
formats="csv.gz csv.xz garmin-bbbike-ascii.zip garmin-bbbike.zip garmin-cycle-ascii.zip garmin-cycle.zip garmin-leisure-ascii.zip garmin-leisure.zip garmin-onroad-ascii.zip garmin-onroad.zip garmin-ontrail-ascii.zip garmin-ontrail.zip garmin-opentopo-ascii.zip garmin-opentopo.zip garmin-openfietslite-ascii.zip garmin-openfietslite.zip garmin-openfietsfull-ascii.zip garmin-openfietsfull.zip garmin-oseam-ascii.zip garmin-oseam.zip garmin-osm-ascii.zip garmin-osm.zip mapsforge-osm.zip mapsme-osm.zip o5m.gz o5m.xz obf.zip opl.xz osm.bz2 osm.gz osm.pbf osm.xz png-cadastre.zip png-google.zip png-hiking.zip png-osm.zip png-urbanight.zip png-wireframe.zip shp.zip srtm-europe.garmin-srtm.zip srtm-europe.obf.zip srtm-europe.osm.pbf srtm-europe.osm.xz srtm.garmin-srtm.zip srtm.obf.zip srtm.osm.pbf srtm.osm.xz svg-cadastre.zip svg-google.zip svg-hiking.zip svg-osm.zip svg-urbanight.zip svg-wireframe.zip mbtiles-openmaptiles.zip"

config=$1

if [ "$1" = "config" ]; then
    : ${warning=2500}
    : ${critical=3500}
     
    cat <<EOF
multigraph pbf_pbf
graph_title Extracts files PBF/Other
graph_vlabel Extracts files PBF/Other
graph_category extractsize
graph_info Number of Files
graph_period minute
osm_pbf.label osm.pbf
osm_pbf.min 0
other.label other
other.min 0
ALL.label All
ALL.min 0

multigraph pbf_pbf_day
graph_title Extracts files PBF/other 24h
graph_vlabel Extracts files PBF/other 24h
graph_category extractsize
graph_info Number of Files
graph_period minute
osm_pbf.label osm.pbf
osm_pbf.min 0
other.label other
other.min 0
ALL.label All
ALL.min 0

multigraph pbf_other
graph_title Extracts files by format
graph_vlabel Extracts files by format
graph_category extractsize
graph_info Number of Files
graph_period minute
EOF

    for f in $formats
    do
        ff=$(echo $f | perl -npe 's/[\.\-]/_/g')
        echo "$ff.label $f"
        echo "$ff.min 0"
        echo "$ff.warning $warning"
        echo "$ff.critical $critical"
    done

    exit 0
fi

echo "multigraph pbf_pbf"
echo "ALL.value" 	`( cd $extract_dir/; ls download | wc -l )`
echo "osm_pbf.value" 	`( cd $extract_dir/; ls download | egrep "\.osm\.pbf$" | wc -l )`
echo "other.value" 	`( cd $extract_dir/; ls download | egrep -v "\.osm\.pbf$" | wc -l )`

echo ""
echo "multigraph pbf_pbf_day"
echo "ALL.value" 	`( cd $extract_dir/; find download -type f -mtime -1 -print | wc -l )`
echo "osm_pbf.value" 	`( cd $extract_dir/; find download -type f -mtime -1 -print | egrep "\.osm\.pbf$" | wc -l )`
echo "other.value" 	`( cd $extract_dir/; find download -type f -mtime -1 -print | egrep -v "\.osm\.pbf$" | wc -l )`

echo ""
echo "multigraph pbf_other"

for f in $formats
do
    ff=$(echo $f | perl -npe 's/[\.\-]/_/g')
    f=$(echo $f | perl -npe 's/(srtm(-europe)?)/${1}.*/g')
    echo "$ff.value"     `( cd $extract_dir/; ls download | egrep "${f}$" | wc -l )`
done
