#!/bin/sh
# Copyright (c) Sep 2011-2023 Wolfram Schneider, https://bbbike.org
#
# usage: /path/to/script [ config ]
#
# get documentation with: perldoc /path/to/script

: << =cut

=head1 NAME

extract-stat  - Plugin to monitor number of statistics from extract/trash

=head1 CONFIGURATION

Configuration parameters for /etc/munin/plugin-conf.d/extract-local
if you need to override the defaults below:

 [bbbike-statistics]
   env.warning   - Generate a warning if number goes above this level
   env.critical  - Generate a critical if number goes above this level

=cut


PATH="/bin:/usr/bin"; export PATH
LANG="C"
extract_dir="/var/cache/extract/"
language="en de fr ru"
extract_time="convert_time extract_time"
home="/usr/local/www/bbbike.org"

trap 'rm -f $tmpfile' 0

config=$1

if [ "$1" = "config" ]; then
  : ${warning="30"}
  : ${critical="100"}
     
  cat <<EOF
multigraph language
graph_title language
graph_vlabel lanuage
graph_category extractadmin
graph_period minute
EOF

  for i in $language
  do
    echo "$i.label $i"
    echo "$i.min 0"
  done

  cat <<EOF
multigraph sub_planet
graph_title sub_planet
graph_vlabel sub_planet
graph_category extractadmin
graph_period minute
EOF

  find $home/world/etc/sub-planet-daily -name '*.poly' | perl -npe 's,.*/,,; s/\.poly//; s/-/_/g' | sort
    awk '{ print $1 ".label " $1; print $1 ".min 0" }'

  cat <<EOF
multigraph run_time
graph_title run_time
graph_vlabel run_time
graph_category extractadmin
graph_period minute
EOF

  for i in $extract_time
  do
    echo "$i.label $i"
    echo "$i.min 0"
  done

  exit 0
fi

tmpfile=$(mktemp)
find $extract_dir -mtime -1 -name '*.json' | xargs egrep -h '"(lang|planet_osm_sub|convert_time|extract_time)" : ' > $tmpfile

echo "multigraph language"
egrep '"lang" : ' $tmpfile | sort | uniq -c | perl -npe 's/[",]//g' |
  awk '{ print $4 ".value " $1 }'

echo ""
echo "multigraph sub_planet"
egrep '"planet_osm_sub" : ' $tmpfile | sort | uniq -c |
  perl -npe 's/""/"full"/; s/[",]//g; s,\.\./.*/,,; s/\.osm\.pbf//; s/-/_/g' |
  awk '{ print $4 ".value " $1 }'

echo ""
echo "multigraph run_time"
egrep '"extract_time" : ' $tmpfile | sed -e 's/,//' -e 's/"//g' | awk '{ s += $3 } END { print "extract_time.value", s/NR }'
egrep '"convert_time" : ' $tmpfile | sed 's/,//' | awk '{ s += $3 } END { print "convert_time.value", s/NR }'

exit 0

#EOF
