#!/bin/sh
# Copyright (c) Sep 2011-2023 Wolfram Schneider, https://bbbike.org
#
# usage: /path/to/script [ config ]
#
# get documentation with: perldoc /path/to/script

: << =cut

=head1 NAME

extract-diskusage  - Plugin to monitor disk usage


=head1 CONFIGURATION

Configuration parameters for /etc/munin/plugin-conf.d/bbbike-local
if you need to override the defaults below:

 [extract-diskusage]
   env.warning   - Generate a warning if disk usage goes above this level
   env.critical  - Generate a critical if disk usage goes above this level

=cut


PATH=/bin:/usr/bin; export PATH
extract_dir=/var/cache/extract
formats="csv.gz csv.xz garmin-bbbike.zip garmin-cycle.zip garmin-leisure.zip garmin-onroad.zip garmin-ontrail.zip garmin-opentopo.zip garmin-openfietslite-latin1.zip garmin-openfietslite.zip garmin-openfietsfull-latin1.zip garmin-openfietsfull.zip garmin-oseam.zip garmin-osm.zip mapsforge-osm.zip organicmaps-osm.zip o5m.gz o5m.xz obf.zip opl.xz osm.bz2 osm.gz osm.pbf osm.xz png-cadastre.zip png-google.zip png-hiking.zip png-osm.zip png-urbanight.zip png-wireframe.zip shp.zip srtm-europe.garmin-srtm.zip srtm-europe.obf.zip srtm-europe.osm.pbf srtm-europe.osm.xz srtm.garmin-srtm.zip srtm.obf.zip srtm.osm.pbf srtm.osm.xz svg-cadastre.zip svg-google.zip svg-hiking.zip svg-osm.zip svg-urbanight.zip svg-wireframe.zip mbtiles-openmaptiles.zip"

config=$1

if [ "$1" = "config" ]; then
    : ${warning=240000000000}
    : ${critical=290000000000}
     
    cat <<EOF
multigraph disksize_pbf
graph_args --base 1024 --lower-limit 0
graph_title Extracts disk usage PBF format
graph_vlabel Extracts disk usage PBF
graph_category extractadmin
graph_info Disk usage
graph_period minute
osm.label Disk usage PBF
osm.min 0
download.label Disk usage PBF+other
download.min 0
EOF

    echo "osm.warning $warning"
    echo "osm.critical $critical"
    echo "download.warning $warning"
    echo "download.critical $critical"

    cat <<EOF
    
multigraph disksize_other
graph_args --base 1024 --lower-limit 0
graph_title Extracts disk usage formats
graph_vlabel Extracts disk usage formats
graph_category extractadmin
graph_info Disk usage
graph_period minute
EOF

    for f in $formats
    do
        ff=$(echo $f | perl -npe 's/[\.\-]/_/g')
        echo "$ff.label $f"
        echo "$ff.min 0"
        echo "$ff.warning $warning"
        echo "$ff.critical $critical"
    done

    exit 0
fi

echo "multigraph disksize_pbf"
echo "osm.value" 	`( cd $extract_dir/ &&  du -ks osm | awk '{ print $1 * 1024 }' )`
echo "download.value" 	`( cd $extract_dir/ && du -ks download | awk '{ print $1 * 1024 }' )`

echo ""
echo "multigraph disksize_other"

du_k=$(mktemp /tmp/munin-bbbike.XXXXXXXXX)
( cd $extract_dir/download && du -k * 2>/dev/null > $du_k )

for f in $formats
do
    ff=$(echo $f | perl -npe 's/[\.\-]/_/g')
    echo "$ff.value"     $( egrep "${f}$" < $du_k | awk '{ s += $1 * 1024 } END { if (NR==0) { print 0} else { print s } }' )
done

rm -f $du_k

exit 0

#EOF

