#!/bin/sh
# Copyright (c) May 2018 Wolfram Schneider, https://bbbike.org
#
# usage: /etc/munin/plugins/extract-wait [ config ]
#
# get documentation with: perldoc /path/to/script

: << =cut

=head1 NAME

extract-wait  - Plugin to monitor running extract wait time in seconds

=head1 ABOUT

[...]

=head1 USAGE

[...]

=head1 CONFIGURATION

Configuration parameters for /etc/munin/plugin-conf.d/munin-node
if you need to override the defaults below:

 [extract-wait]
   env.wait_warnings - Generate a warning if average wait time goes above this level 
   env.wait_critical - Generate a critical if average wait time goes above this level

=cut


PATH=/bin:/usr/bin; export PATH

config=$1

case $0 in 
    *-pro* ) pro="pro"
              : ${extract_dir="/var/cache/extract-pro"}
            ;;
    *)        : ${extract_dir="/var/cache/extract"}
            ;;
esac

extract_dir_confirmed=$extract_dir/confirmed2

if [ "$1" = "config" ]; then
    : ${wait_warning=40}
    : ${wait_critical=360}

     
    cat <<EOF
graph_title Extracts wait time $pro
graph_vlabel Extracts wait time $pro
graph_category extract
graph_info Waiting extract time $pro
graph_period minute
wait.label Waiting time $pro
wait.min 0
EOF

echo "wait.warning $wait_warning"
echo "wait.critical $wait_critical"


    exit 0
fi

#############################################
# main
#
echo "wait.value" $(ls $extract_dir_confirmed/*json 2>/dev/null | wc -l) 
# wait_min
# wait_max
# wait_average
# wait_median

# EOF
