#!/bin/sh
# Copyright (c) Sep 2011-2018 Wolfram Schneider, https://bbbike.org
#
# usage: /etc/munin/plugins/extract-users [ config ]
#
# get documentation with: perldoc /path/to/script

: << =cut

=head1 NAME

extract-users  - Plugin to monitor running extract users

=head1 ABOUT

[...]

=head1 USAGE

[...]

=head1 CONFIGURATION

Configuration parameters for /etc/munin/plugin-conf.d/munin-node
if you need to override the defaults below:

 [bbbike-extract-users]
   env.warning   - Generate a warning if number of users goes above this level
   env.critical  - Generate a critical if number of users goes above this level
   env.users_warnings - [...]
   env.users_critical - [...]

=cut


PATH=/bin:/usr/bin; export PATH

config=$1

case $0 in 
    *-pro* ) pro="pro"
              : ${extract_dir="/var/cache/extract-pro"}
            ;;
    *)        : ${extract_dir="/var/cache/extract"}
            ;;
esac

extract_dir_running=$extract_dir/running

if [ "$1" = "config" ]; then
    : ${warning=240}
    : ${critical=400}

    : ${users_warning=240}
    : ${users_critical=400}
     
    cat <<EOF
graph_title Extracts users $pro
graph_vlabel Extracts users $pro
graph_category extract
graph_info Running extract users $pro
graph_period minute
users.label Running users $pro
users.min 0
EOF

echo "users.warning $users_warning"
echo "users.critical $users_critical"

    exit 0
fi

#############################################
# main
#

echo "users.value" \
  $(egrep -h email $(find $extract_dir/trash -type f -mtime -1 ) | sed 's/,$//' | sort -u | wc -l)

# EOF
