#!/bin/sh
# Copyright (c) Sep 2011-2018 Wolfram Schneider, https://bbbike.org
#
# usage: /etc/munin/plugins/extract-users [ config ]
#
# get documentation with: perldoc /path/to/script

: << =cut

=head1 NAME

extract-users  - Plugin to monitor running extract users

=head1 ABOUT

[...]

=head1 USAGE

[...]

=head1 CONFIGURATION

Configuration parameters for /etc/munin/plugin-conf.d/munin-node
if you need to override the defaults below:

 [bbbike-extract-users]
   env.warning   - Generate a warning if number of users goes above this level
   env.critical  - Generate a critical if number of users goes above this level
   env.users_warnings - [...]
   env.users_critical - [...]

=cut


PATH=/bin:/usr/bin; export PATH

config=$1

case $0 in 
    *-pro* ) pro="pro"
              : ${extract_dir="/var/cache/extract-pro"}
            ;;
    *)        : ${extract_dir="/var/cache/extract"}
            ;;
esac

extract_dir_running=$extract_dir/running

if [ "$1" = "config" ]; then
    : ${warning=300}
    : ${critical=500}

    : ${users_warning=300}
    : ${users_critical=500}
     
    cat <<EOF
graph_title Extracts users $pro
graph_vlabel Extracts users $pro
graph_category extract
graph_info Running extract users $pro
graph_period minute
users3.label Running users 3h $pro
users3.min 0
users12.label Running users 12h $pro
users12.min 0
users.label Running users 24h $pro
users.min 0
EOF

echo "users.warning $users_warning"
echo "users.critical $users_critical"
echo "users3.warning $users_warning"
echo "users3.critical $users_critical"
echo "users12.warning $users_warning"
echo "users12.critical $users_critical"

    exit 0
fi

#############################################
# main
#

echo "users.value" $(find $extract_dir/trash   -type f -mtime  -1 -print0 | xargs -0 egrep -h email | sed 's/,$//' | sort -u | wc -l)
echo "users3.value" $(find $extract_dir/trash  -type f -mmin -180 -print0 | xargs -0 egrep -h email | sed 's/,$//' | sort -u | wc -l)
echo "users12.value" $(find $extract_dir/trash -type f -mmin -720 -print0 | xargs -0 egrep -h email | sed 's/,$//' | sort -u | wc -l)

# EOF
