#!/bin/sh
# Copyright (c) Sep 2011-2017 Wolfram Schneider, https://bbbike.org
#
# usage: /etc/munin/plugins/extract-stale [ config ]
#
# get documentation with: perldoc /path/to/script

: << =cut

=head1 NAME

extract-stale  - Plugin to monitor running stale extract jobs

=head1 ABOUT

[...]

=head1 USAGE

[...]

=head1 CONFIGURATION

Configuration parameters for /etc/munin/plugin-conf.d/munin-node
if you need to override the defaults below:

 [bbbike-extract-stale]
   env.warning   - Generate a warning if number of stale jobs goes above this level
   env.critical  - Generate a critical if number of stale jobs goes above this level
   env.stale_warnings - [...]
   env.stale_critical - [...]

=cut


PATH=/bin:/usr/bin; export PATH
LANG="C"; export LANG

config=$1

case $0 in 
    *-pro* ) pro="pro"
              : ${extract_dir="/var/cache/extract-pro"}
            ;;
    *)        : ${extract_dir="/var/cache/extract"}
            ;;
esac

extract_dir_running=$extract_dir/running

if [ "$1" = "config" ]; then
    : ${warning=0:0}
    : ${critical=0:2}
    : ${stale_warning=0:0}
    : ${stale_critical=0:2}
     
    cat <<EOF
graph_title Extracts crashed $pro
graph_vlabel Extracts crashed $pro
graph_category extractadmin
graph_info Stale extract jobs $pro
graph_period minute
stale.label Stale jobs $pro
stale.min 0
EOF

echo "stale.warning $stale_warning"
echo "stale.critical $stale_critical"

    exit 0
fi

#############################################
# main
#
echo "stale.value" $(cd $extract_dir_running && find . -cmin +400 ! -name . -type d -print | wc -l)

# EOF
