#!/bin/sh
# Copyright (c) Sep 2011-2021 Wolfram Schneider, https://bbbike.org
#
# usage: /etc/munin/plugins/extract-files [ config ]
#
# get documentation with: perldoc /path/to/script

: << =cut

=head1 NAME

extract-download  - Plugin to monitor number download traffic

=head1 ABOUT

[...]

=head1 USAGE

[...]

=head1 CONFIGURATION

Configuration parameters for /etc/munin/plugin-conf.d/munin-node
if you need to override the defaults below:

 [bbbike-extract-files]
   env.warning   - Generate a warning if number of files goes above this level
   env.critical  - Generate a critical if number of files goes above this level

=cut


PATH=/bin:/usr/bin; export PATH
LANG=C
log_dir=/var/log/lighttpd

config=$1

if [ "$1" = "config" ]; then
    : ${warning=2500}
    : ${critical=3500}
     
    cat <<EOF
multigraph download
graph_title download traffic
graph_vlabel download traffic out
graph_category extractsize
graph_period minute
planet_latest.label planet-latest
planet_latest.min 0
planet_daily.label planet-daily
planet_daily.min 0
other.label other
other.min 0
ALL.label All
ALL.min 0
EOF

    exit 0
fi

cd $log_dir

days=30
log_file=$(mktemp /tmp/munin-extract-download.XXXXXXXX)
zcat -f $(ls -tr download* | tail -n $days) > $log_file

echo "multigraph download"
echo "ALL.value" 		$( awk '{ a+=$10 } END { print a }' $log_file )
echo "planet_latest.value" 	$( egrep '/planet-latest'  	     $log_file | awk '{ a+=$10 } END { print a }' )
echo "planet_daily.value" 	$( egrep '/planet-daily'  	     $log_file | awk '{ a+=$10 } END { print a }' )
echo "other.value" 		$( egrep -v '/planet-(daily|latest)' $log_file | awk '{ a+=$10 } END { print a }' )

rm -f $log_file

#EOF
