#!/bin/sh
# Copyright (c) Sep 2011-2023 Wolfram Schneider, https://bbbike.org
#
# usage: /path/to/script [ config ]
#
# get documentation with: perldoc /path/to/script

: << =cut

=head1 NAME

extract-http404  - Plugin to monitor number of HTTP 404 errors in access log

=head1 CONFIGURATION

Configuration parameters for /etc/munin/plugin-conf.d/bbbike-local
if you need to override the defaults below:

 [bbbike-extract-files]
   env.warning   - Generate a warning if number goes above this level
   env.critical  - Generate a critical if number goes above this level

=cut


PATH="/bin:/usr/bin"; export PATH
LANG="C"
log_dir="/var/log/lighttpd"
log_files="api.bbbike.log bbbike.log dev.bbbike.log download.bbbike.log extract.bbbike.log m.bbbike.log search.bbbike.log"

config=$1

if [ "$1" = "config" ]; then
  : ${warning="200"}
  : ${critical="600"}
     
  cat <<EOF
multigraph 
graph_title HTTP 404
graph_vlabel HTTP 404
graph_category extract
graph_period minute
EOF

  for file in $log_files
  do
    item=$(basename $file | sed 's/\./_/g')
    echo "$item.label $item"
    echo "$item.min 0"
  done

  exit 0
fi

cd $log_dir

echo "multigraph download"

for file in $log_files
do
  item=$(basename $file | sed 's/\./_/g')
  echo -n "$item.value "
  grep ' 404 ' $file | grep -c -E -v 'bot|/apple|cyberscan' 
done

#EOF
