###############################################################
# Copyright (c) 2015 Wolfram Schneider, http://bbbike.org
#
# poly setup
#

all: help

update update-poly:
	cd ../../.. && ./world/bin/sub-planet.pl 
	git diff .

help:
	@echo "make [ update ]"
	@echo ""

